### ISSUE TITLE
Moving error

### ISSUE THREAD

**Issue by borkowsky** [Annoraaq/grid-engine#109]
Hi. Sometimes when i try to move character after create scene, char just change facing direction and not move.
How can i fix this issue?

**Comment by borkowsky** [comment]
I captured video.
https://youtube.com/shorts/kXTXcDymwb0?feature=share

**Comment by Annoraaq** [comment]
Are there any errors shown in the console?

Are you recreating the plugin after loading the scene? Or did the tilemap change and the plugin is still using the reference to the old tilemap?

It looks to me like the plugin thinks that all directions are blocked. This could be the case if the tilemap is unloaded. But I am just guessing.

**Comment by borkowsky** [comment]
No errors in console. I just go to combat scene, then to death scene and go to map scene from death scene.

**Comment by Annoraaq** [comment]
I will try to reproduce it with a change of scenes.

**Comment by borkowsky** [comment]
> I will try to reproduce it with a change of scenes.

It happens when i change player position at server and server emit event (player patched) which call player position synch at map. When player moving i restart scene (clear all events, destroy map and other objects). I do restart scene because i need to change player position without moving animation (because it calls another synch at server, i dont need it, thats why i so need ur new announced setTilePosition() method ;))
Then after scene restarted (it calls initialization of map, plugins, add players, npcs etc), player cant move.
I hope it helps to understanding problem. 
P.s. sorry for my english

**Comment by borkowsky** [comment]
I think i cant change player position immediately,  without playing move animation and without restarting scene (without recreating plugin)

**Comment by Annoraaq** [comment]
In a different thread you mentioned that you get the character directly via `let character = this.gridEngine.gridCharacters.get('char-id')`

Does it help if you call `character.setTilePosition(new Phaser.Math.Vector2(<X_POS>, <Y_POS>)`?

That does not explain the bug but it could help you out until it is fixed as a workaround. And as soon as I expose `setTilePosition` to the public API you can safely use it.

**Comment by borkowsky** [comment]
> In a different thread you mentioned that you get the character directly via `let character = this.gridEngine.gridCharacters.get('char-id')`
> 
> Does it help if you call `character.setTilePosition(new Phaser.Math.Vector2(<X_POS>, <Y_POS>)`?
> 
> That does not explain the bug but it could help you out until it is fixed as a workaround. And as soon as I expose `setTilePosition` to the public API you can safely use it.

Yes, it should be very helpful in my case, i dont know how to fix this problem by another way.

**Comment by Annoraaq** [comment]
Ok. So just to be clear: in theory you should already be able to use it like this. So you can try it out:

```
let character = this.gridEngine.gridCharacters.get('char-id')

Does it help if you call character.setTilePosition(new Phaser.Math.Vector2(<X_POS>, <Y_POS>));
```

But please keep in mind that this is only a workaround because `this.gridEngine.gridCharacters` is internal to the plugin. But I will add the `setTilePosition` method to the API of the plugin and let you know. In the meantime please let me know if the above approach works.

**Comment by borkowsky** [comment]
> Ok. So just to be clear: in theory you should already be able to use it like this. So you can try it out:
> 
> ```
> let character = this.gridEngine.gridCharacters.get('char-id');
> 
> character.setTilePosition(new Phaser.Math.Vector2(<X_POS>, <Y_POS>));
> ```
> 
> But please keep in mind that this is only a workaround because `this.gridEngine.gridCharacters` is internal to the plugin. But I will add the `setTilePosition` method to the API of the plugin and let you know. In the meantime please let me know if the above approach works.

```
setTilePosition()
```
For character works now? Is it internal method?

**Comment by Annoraaq** [comment]
That's correct. In fact, the plugin uses this method to set the tile position of the character on initialization, so it should work I guess. But it will not do anything while the character is moving (because that would cause chaos).

**Comment by borkowsky** [comment]
> That's correct. In fact, the plugin uses this method to set the tile position of the character on initialization, so it should work I guess. But it will not do anything while the character is moving (because that would cause chaos).
> 

I will try that tomorrow and i write message to you with result of this code. Thanks for the answers )

**Comment by Annoraaq** [comment]
👍  You're welcome 🙂

**Comment by borkowsky** [comment]
>  You're welcome

Hey. Ur advice works as expected, thanks) I still waiting new methods ;)

**Comment by Annoraaq** [comment]
That is great. I will add it to the public api and let you know as soon as it's available.

**Comment by Annoraaq** [comment]
Hi @borkowsky

is this still an issue? I am having trouble to reproduce this. When I restart the scene via:

```js
this.registry.destroy();
this.events.off();
this.scene.restart();
```

Then everything works as expected. If it is still an issue, can you provide a mininum example that breaks?

Thanks

**Comment by borkowsky** [comment]
Hi @Annoraaq . I go to try ur example then i give answers

**Comment by borkowsky** [comment]
Hi @Annoraaq 
All works as expected now, thanks ;)
