### ISSUE TITLE
moveTo potential issue

### ISSUE THREAD

**Issue by Mteuahasan** [Annoraaq/grid-engine#110]
Hello,

I'm using your engine in order to build my project. It is awesome overall congrats !

I just ran into an issue on my project : when I use moveTo on any character, it result in the character going back and forth around the destination tile. Is that a bug or is there any parameter I'm missing ?

Here is a video of what I am try to explain : https://streamable.com/b7lalj

Thank you !

**Comment by Annoraaq** [comment]
Hi @Mteuahasan

You are absolutely right. It is also broken in the example section. Seems like some update broke it. Thank you for pointing that out! 🙂 

I will let you know as soon as it is fixed.

I am glad you like the engine. If you have more feedback, we are happy for every input 👍 

👋

**Comment by Mteuahasan** [comment]
Thank you very much !
I do have another feedback, I'll post another issue 😄

**Comment by Annoraaq** [comment]
@Mteuahasan Should be solved in 1.12.3. Can you confirm?
Thanks again for pointing it out.

**Comment by Mteuahasan** [comment]
I do confirm, thank you 🤩
