### ISSUE TITLE
Webpack "Unexpected Token" error in Create React App and other webpack based libraries

### ISSUE THREAD

**Issue by mikedane** [Annoraaq/grid-engine#117]
I'm trying to use Grid Engine in a React app and am running into a problem getting it to build. At this point, I'm unable to even import `GridEngine`. without an "Unexpected Token" error.

I've been able to replicate this error using Create React App, Gatsby, Storybook, as well as code sandbox. Is this a known error and the library is simply not compatible with these environments, or am I missing something from the docs?

Minimal Create React App repo demonstrating problem - https://github.com/mikedane/grid-engine-bug-demo
Code Sandbox repo with similar error - https://codesandbox.io/s/cool-worker-q0cgv?file=/src/App.js

Any help would be appreciated!

**Comment by Annoraaq** [comment]
Hey mikedane, I have actually never tested it with React. I will check it out and let you know what I found out.

Thanks for letting us know 🙂

**Comment by awweather** [comment]
I have the same problem using Vue :)

**Comment by Annoraaq** [comment]
@mikedane @awweather 
I found out that I need to compile down to es2016 instead of esnext. Can you confirm that the problem is solved in 1.14.1?

**Comment by mikedane** [comment]
Looks like the patch fixed it! Can confirm it's working now. Thanks for the quick response, loving this library!

**Comment by awweather** [comment]
@Annoraaq It's fixed! thanks for the quick reply
