### ISSUE TITLE
help how to use in js?

### ISSUE THREAD

**Issue by lendsp** [Annoraaq/grid-engine#120]
i tried npm i --save grid-engine

and add <script src="GridEngine-1.12.2.min.js"></script> in index.html 

` this.gridEngine.create(cloudCityTilemap, gridEngineConfig);`

```
game3.js:84 Uncaught TypeError: Cannot read property 'create' of undefined
    at initialize.create (game3.js:84)
    at initialize.create (GridEngine-1.12.2.min.js:20)
    at initialize.loadComplete (GridEngine-1.12.2.min.js:20)
    at initialize.s.emit (GridEngine-1.12.2.min.js:1)
    at initialize.loadComplete (GridEngine-1.12.2.min.js:50)
    at initialize.fileProcessComplete (GridEngine-1.12.2.min.js:50)
    at initialize.onProcessComplete (GridEngine-1.12.2.min.js:7)
    at Image.data.onload (GridEngine-1.12.2.min.js:7)

```

**Comment by DouglasDev** [comment]
Did you add it is a plugin to Phaser?
Example:
```
var game = new Phaser.Game({
  type: Phaser.AUTO,
  width: 400,
  height: 300,
  scene: {
    preload,
    create,
  },
  plugins: {
    scene: [
      {
        key: 'gridEngine',
        plugin: GridEngine,
        mapping: 'gridEngine',
      },
    ],
  },
})
```

**Comment by Annoraaq** [comment]
Hey @lendsp

First, you need to decide for one option: npm or web. If you want to include it via <script> tag (which a call web) then you don't need to run `npm i`. It is hard to say why your error occurs without more context. Can you provide more code?

One reason could be what @DouglasDev suggested. If you don't add it as a plugin, it will not be known within your phaser functions. Another reason could be that you are trying to reference it from outside of Phaser's functions like `update`, `create`, etc.

**Comment by lendsp** [comment]
Thank @DouglasDev 

i had a mistake. i don't have put the the another scene inside plugins

Thank @Annoraaq 

I really don't really know what I'm doing
trying to mix the gridengine with socket.io, and learning from scratch.

I even had something that was more advanced, but it was complicated to have control of the sprites, so I'm starting over and I'm going to put more emphasis on the gridEngine
