### ISSUE TITLE
setSpeed not working

### ISSUE THREAD

**Issue by Mteuahasan** [Annoraaq/grid-engine#131]
Hello,

I'm facing an issue with the setSpeed method. The property speed of the character is updated but the speed does not change. Maybe the method is not designed to be called on the fly ? For the context, I'm trying to speed up my character when pressing the shift key.

Thank you !

**Comment by Annoraaq** [comment]
I can confirm that this is a bug. The method was designed for exactly your use case.

Thank you for telling! I will let you know as soon as it is fixed.

**Comment by Annoraaq** [comment]
Fixed with 2.2.0
