### ISSUE TITLE
Add moveOnPath method

### ISSUE THREAD

**Issue by Annoraaq** [Annoraaq/grid-engine#134]
Add a method that allows passing a path for the character to move along.

**Comment by xLink** [comment]
this would be very useful for what im building, could it be viable to add a loop property? to make it auto restart the path move when finished

**Comment by Annoraaq** [comment]
Regarding the loop functionality. Do you have something like this in mind: 

If you have a path consisting of adjacent tile positions like: [pos1, pos2, ... posN] and the char arrives at posN. Should he then walk back again (walk the path in reverse order)?

**Comment by xLink** [comment]
![animatedTiles](https://user-images.githubusercontent.com/217433/130472354-f7c2da7f-9389-415b-aa60-acb61a1c4fba.gif)
this gif describes what i mean quite nicely, (its just me running around a house) but a npc with the 4 corners of the house being its path, once it gets to the end of the path, it just starts again and runs to pos1 if its not already

**Comment by Annoraaq** [comment]
When implemented you will have an observable that notifies you when the character has reached the target. Then you can simply restart the movement. So this kind of looping should not be a problem.

**Comment by Annoraaq** [comment]
Closing this, because it can be achieved using [isPositionAllowedFn](https://annoraaq.github.io/grid-engine/typedoc/interfaces/MoveToConfig.html#isPositionAllowedFn). Also see this example: https://annoraaq.github.io/grid-engine/examples/pathfinding-restriction.html
