### ISSUE TITLE
NPM errors when installing GridEngine with Phaser 3.55.x

### ISSUE THREAD

**Issue by splashsky** [Annoraaq/grid-engine#148]
Title. This should be able to be easily fixed by upping our dependency version in the project from `~3.54.0` to `~3.55.0`. I'm not sure about dependency trees though. 😛

**Comment by Annoraaq** [comment]
Good point. I will check it out.

**Comment by Annoraaq** [comment]
While I was not able to reproduce any errors when using the new Phaser version, I still updated the dependency. Can you please check if you still observe any errors? If so, could you provide those?

**Comment by splashsky** [comment]
Attempting to install GridEngine with `npm i grid-engine` no longer gives me a dependency error. We're good to go! 👍🏻 

Thanks for the quick fix, guy :smile:
