### ISSUE TITLE
Getting a tile

### ISSUE THREAD

**Issue by splashsky** [Annoraaq/grid-engine#154]
I'm not sure if the ability was ever added, but one feature that was valuable related to the `getFacingDirection` method is that we would be able to get information on a tile adjacent to the player - similar to the way we can get the tile the player has stepped on via `onEnter`. Does this ability exist for `getFacingDirection`, and if not can it be added?

We might want to consider creating example code with greater functionality for these various use-cases. At present we do a good job of showing most of what's possible, but the GridEngine API is still pretty scarce on examples. I'd like to help with this again as soon as time allows me.

**Comment by Annoraaq** [comment]
At the moment no such method exists. But it can be achieved by using the methods already there. All you need is `getFacingDirection` and `getPosition`. If you know the position of the character and its facing direction then its simple to get the position of the facing adjacent tile. It could be something like this:

```javascript
function getPosInFacingDirection(charId) {
  const pos = this.gridEngine.getPosition(charId);
  const dir = this.gridEngine.getFacingDirection(charId);
  if (dir == "up") {
    return { ...pos, y: pos.y - 1 };
  } else if (dir == "down") {
    return { ...pos, y: pos.y + 1 };
  } else if (dir == "left") {
    return { ...pos, x: pos.x - 1 };
  } else if (dir == "right") {
    return { ...pos, x: pos.x + 1 };
  }
}
```

Of course it might be handy to put that in a method like `getFacingPosition` or something.

Sure, more examples are always good. 
I think the API itself is documented in terms of that there is no public method or configuration option which has no section in the docs. However, it could be much more detailed in many places. So there is definitely room for improvement :) Would be great if you can support there 👍

**Comment by splashsky** [comment]
I had to correct my previous statement - all the important API tidbits are there. It's just exposing/demo'ing some more real world applications would be neato! Good job on the docs by the way, I've been able to tinker with a personal project a fair bit with it.

I would second implementing a method to retrieve not just the position of a tile, but also the properties of a tile. I think this sort of thing would be appropriate for the engine to handle based solely on the fact that GE actually handles all interactions with the map, so extrapolating a feature like that seems fitting.

**Comment by Annoraaq** [comment]
What do you mean by properties? The custom properties that you can set in Tiled?

**Comment by splashsky** [comment]
Yes, although it's apparent you can use Phaser's tilemap methods to do "getTileAt", which works swell. I just wonder if it would be too redundant to give GridEngine the ability to maybe more succinctly getTileProps? At current the best example of getting props on tiles we have is

```js
function hasTrigger(tilemap, position) {
  return tilemap.layers.some((layer) => {
    const tile = tilemap.getTileAt(position.x, position.y, false, layer.name);
    return tile?.properties?.trigger;
  });
}
```

whereas I could envision a cleaner solution to be

```js
function hasTrigger(position, layer) {
  return this.GridEngine.getTileAt(position.x, position.y, layer)?.trigger;
  // and perhaps a way to confirm whether a tile has a prop, i.e.
  // this.GridEngine.getTileAt(pos.x, pos.y, layer)?.hasProp("prop name");
}

**Comment by Annoraaq** [comment]
How to you suggest to merge the properties of the several layers?

**Comment by splashsky** [comment]
After learning more about the `some()` method I see your point. I suppose this sort of function would be best implemented on a per-project basis. I'll see if I can conceptualize some useful generic utilities.

**Comment by Annoraaq** [comment]
I created an issue for this: #172
