### ISSUE TITLE
Build error: Could not resolve "grid-engine/dist/Direction/Direction"

### ISSUE THREAD

**Issue by splashsky** [Annoraaq/grid-engine#156]
Howdy! I was working on getting all the proper typing passed to various functions, and while I was working on the movement code I tried to use the Direction enum as the parameters for movement. However, when trying to build I got the following error...

```
> .\node_modules\.bin\esbuild src/Game.ts --bundle --outfile=public/game.js

 > src/scenes/MainScene.ts:2:26: error: Could not resolve "grid-engine/dist/Direction/Direction" (mark it as external to exclude it from the bundle)
    2 │ import { Direction } from "grid-engine/dist/Direction/Direction";
      ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1 error
```

However, I'm 100% certain that the `Direction.d.ts` file is precisely where it should be - it was suggested and autofilled by the editor, after all.

Is this an issue you've come across? Is there a fix?

**Comment by splashsky** [comment]
I've temporarily fixed this issue by creating my own helper ts file with a Direction enum. I'll continue to read into what the issue could be.

**Comment by Annoraaq** [comment]
This is my fault. I exposed the Direction interface directly, because it is needed for the API. So no need to include a deep link to the file like your editor suggested anymore.

It should work via: 
```import { GridEngine, GridEngineConfig, Direction } from "grid-engine";```

**Comment by splashsky** [comment]
Attempted to import it that way, but alas...

```
Module '"grid-engine"' declares 'Direction' locally, but it is not exported.ts(2459)
GridEngine.d.ts(3, 10): 'Direction' is declared here.
```

Maybe need an explicit type definition in there?

**Comment by Annoraaq** [comment]
Are you using version 2.4.0?

**Comment by Annoraaq** [comment]
https://codesandbox.io/s/eloquent-rgb-0heom?file=/src/index.ts:0-129

Here is a minimal working example.

**Comment by splashsky** [comment]
> Are you using version 2.4.0?

This appears to have been the issue. As of updating to 2.4.0 I no longer have that notice. Thanks, Anno! :smile:
