### ISSUE TITLE
movementStopped does not catch the destination tile

### ISSUE THREAD

**Issue by splashsky** [Annoraaq/grid-engine#159]
After some testing, I've noticed that `movementStopped` doesn't register on the tile you stop moving on, but instead the tile behind you, in the direction you came. For example, if you're on (1, 1) and you move right to (4, 1), then the position you get in `movementStopped` is (3, 1).

I don't imagine this behavior is intentional, and it really messes with using this observable for it's intended purpose.

**Comment by Annoraaq** [comment]
`movementStopped` is intended to be used in order to create custom animations, not for position detection. Position detection should be done via `getPosition` or the `positonChangeStarted` and `positonChangeStopped` observables.

The weird results you are observing might come from the fact that `movementStopped` is not returning a position but a characterId and a direction:

https://annoraaq.github.io/grid-engine/api/methods.html

**Comment by splashsky** [comment]
> ... I checked the code and I think that this observable also fires before the movement is stopped so it comes too late. I will fix this order of calling the observables and then you should be able to subscribe to `movementChangeFinished` and check if the character is moving or not.

Excellent! This would be a huge boon for me. The reason I wasn't using `positionChangeStopped` was because that observable fires every instance that the character has shifted tiles - i.e. it fires every time the character steps on a new tile. This behavior is expected, and I wouldn't want that to change. I suppose the naming of `movementStopped` was a bit of a misnomer.

Either way, thanks for looking into it. :smile:

**Comment by Annoraaq** [comment]
@splashsky just to keep you up to date: I have to change some core aspects of the movement in order to get this fixed. Therefore it takes a bit longer than expected.

**Comment by splashsky** [comment]
Ah no problem - don't rush it. I'm still working on visuals and playing with Phaser-specific mechanics, so take all the time you need my guy. 😄

**Comment by Annoraaq** [comment]
@splashsky closed with 2.4.1

Please let me know if your problem still occurs.

**Comment by splashsky** [comment]
So what would be the new method by which I'd check for the final destination tile? Is there a new `movementChangeStopped`?

**Comment by splashsky** [comment]
Upon testing with both `movementStarted` and `movementStopped`, the issue still exists. This screenshot is the console after moving one tile to the right.

![image](https://user-images.githubusercontent.com/12104206/125393228-2a90b880-e36d-11eb-83d9-3c5af02f62c9.png)

**Comment by Annoraaq** [comment]
@splashsky I can see it working in my simple example here:
https://codesandbox.io/s/restless-https-nuvkk?file=/src/index.js

To be clear about how the behavior should be:
If you subscribe to movementStopped and access getPosition() from within the subscription, you should observe the current position. Moreover, movementStopped does not fire on a direction change anymore but only the character stops.

**Comment by Annoraaq** [comment]
@splashsky Seems like I forgot to actually build the project before releasing 1.4.1...

It should work with 1.4.2!

**Comment by splashsky** [comment]
Haha, working perfectly! Thanks a ton for your work, man. If you ever open a $5/mo sponsor spot, lemme know 😉

**Comment by Annoraaq** [comment]
You are welcome! I will let you know. Thanks a lot for your support🙂
