### ISSUE TITLE
Big docs update

### ISSUE THREAD

**Issue by splashsky** [Annoraaq/grid-engine#160]
I'm working on a substantial docs update at the moment.

Current changes:
- Switching from Jekyll to Hugo (Ruby to Go)
- More modern theme includes table of contents sidebar and cleaner mobile view
- An additional dark mode, for those late night game dev sessions!
- Cleaning up example pages and improving per-feature documentation

Should be ready within a week or so. Have a lot to rewrite!

**Comment by Annoraaq** [comment]
Sounds great! 👍 Thank you

**Comment by splashsky** [comment]
First peek at the update. Most important thing for me in this rewrite is cleanliness, and I hope to expand on more complicated examples. I also want to make the API and Methods pages easier to navigate, and to read.

Almost there - just takes a while to redo every single example page 🤣 

![image](https://user-images.githubusercontent.com/12104206/123829243-e6f77280-d8c7-11eb-915d-2e8cc3102213.png)

**Comment by splashsky** [comment]
I apologize for the delay - just confirming I am still working on the docs update and they're coming along great!

Technology has switched again as needs changed throughout the initial work. I ditched Hugo and Jekyll in favor of Docusaurus; a JS solution I rather like. Looking forward to publishing the updated docs!

The API is also getting much more fleshed out, with individual pages for each relevant interface or type. Examples might take a bit longer to rewrite, however.

**Comment by splashsky** [comment]
An example of method/API formatting, as it's come to be

![image](https://user-images.githubusercontent.com/12104206/125142356-2484a880-e0dd-11eb-8dc2-ac7adc4ac8dc.png)

**Comment by Annoraaq** [comment]
Looks great!

**Comment by splashsky** [comment]
Okay, so most all the work is done now. All that's left is to handle migrating the examples, but running into some `<script>` related issues thanks to React. Working on it asap!

**Comment by Annoraaq** [comment]
I went with Gridsome now and a self made theme. It is also easier now to add examples.
