### ISSUE TITLE
Expose isCreated or a property indicating the engine has been initialized/created

### ISSUE THREAD

**Issue by awweather** [Annoraaq/grid-engine#165]
I have some external systems that run outside of phaser.  I'd like for them to be able to tell when the grid engine has initialized so that I can prevent calls into them too early.  Is there a way to do this?  I see an isCreated property but its private.

**Comment by Annoraaq** [comment]
Hi @awweather

the private isCreated property indicates whether the create method of the plugin already has been called. This is usually done in the create method of phaser. I think in your situation it might be cleaner to check whether phaser has already been initialized if that is possible somehow.

You could also call some function in the create method of phaser or set a global variable to indicate that state change (if phaser does not provide something like this already).

**Comment by lendsp** [comment]
> I have some external systems that run outside of phaser. I'd like for them to be able to tell when the grid engine has initialized so that I can prevent calls into them too early. Is there a way to do this? I see an isCreated property but its private.

i had problems with socket.io my solution was to use timedevent in the create() function to make the middle field. I don't know if this is nonsense...

**Comment by awweather** [comment]
Thanks all, I think you've shared some ideas of how I can handle this!  I appreciate the quick feedback.

**Comment by Annoraaq** [comment]
@awweather can I close this issue or is this still an issue?

**Comment by awweather** [comment]
@Annoraaq yes thank you, I found another way.
