### ISSUE TITLE
Layer render order and collision bugs

### ISSUE THREAD

**Issue by gitwikc** [Annoraaq/grid-engine#191]
### Expected behaviour
* The layers in the map render as configured in tilemap editor.
* The player sprite should be rendered in the order as specified in `playerSprite.setDepth`

## Bug :bug: 
* The playerSprite always renders as the top layer (above all layers in the map) even though render order is set in `playerSprite.setDepth` and there are layers in the map that should be rendered over the playerSprite
* The playerSprite renders on top of all map layers even after `playerSprite.setDepth(0)`

### Expected behaviour
* The player sprite should be able to move freely on the map except on the tiles that are colliding tiles as specified in `collisionTilePropertyName` in the `GridEngineConfig` object
### Bug :bug: 
* The player doesn't collide with the colliding tiles but sometimes just stops moving at a tile *as if* it's a colliding tile even though it doesn't have collides property true

> Same issue encountered on the example on [**Basic Movement**](https://annoraaq.github.io/grid-engine/examples/basic-movement.html) in the documentation. The player sometimes stops at tiles that *aren't supposed to be colliding tiles*

## My code
* [Gist with the files](https://gist.github.com/gitwikc/b5200b03df9ea341208af3e6f86393ba)
* Layers of map are created in `GameScene.js` on [line 41](https://gist.github.com/gitwikc/b5200b03df9ea341208af3e6f86393ba#file-gamescene-js-L41)
* Player sprite render order set in `GameScene.js` on [line 27](https://gist.github.com/gitwikc/b5200b03df9ea341208af3e6f86393ba#file-gamescene-js-L27)
* I configure `grid-engine` in `GameScene.js` on [line 74](https://gist.github.com/gitwikc/b5200b03df9ea341208af3e6f86393ba#file-gamescene-js-L74)

**Comment by Annoraaq** [comment]
Hey @gitwikc 

For the first issue I can give you a simple solution. GridEngine will overwrite your character sprite's depth property. That is necessary to correctly layer all the characters with respect to each other.

In order to place the characters at the correct layer of the tilemap there is the tile layer property `ge_alwaysTop`: https://annoraaq.github.io/grid-engine/usage/layer-properties.html

If set to true on a tilemap layer, this layer will be rendered on top of all characters. There can also be several layers with this property.

However, I am currently working on a feature called _character layers_ that allows more control over layering. It will allow to have multiple char layers in your tilemap (#182)

I will try to reproduce the collision issue and come back to you.

**Comment by Annoraaq** [comment]
I tried to reproduce the issue with the collision but without success. You said it also occurs on the basic movement example. Do you mean in the online version of that example [here](https://annoraaq.github.io/grid-engine/examples/basic-movement.html)? If so, could you give more information on which tiles do not block as expected?

Do you maybe have a minimum working example that demonstrates the issue? With assets, map and everything. That would help reproducing the issue.

**Comment by gitwikc** [comment]
> I tried to reproduce the issue with the collision but without success. You said it also occurs on the basic movement example. Do you mean in the online version of that example [here](https://annoraaq.github.io/grid-engine/examples/basic-movement.html)? If so, could you give more information on which tiles do not block as expected?
> 
> Do you maybe have a minimum working example that demonstrates the issue? With assets, map and everything. That would help reproducing the issue.

@Annoraaq 

Yes, the online version example for Basic Movement in the docs,

![image](https://user-images.githubusercontent.com/60361305/133203623-83b8fd4c-d2fb-4b3b-ad56-6acd194efd5c.png)


### Bug
In the above image I am actually pressing the down key while the sprite is at the position as shown, but the sprite does not walk downwards. Also it doesn't move leftwards. But moves right. It seems like it is colliding with tiles in that area. Is there supposed to be a colliding tile below or on the left of the tile on which the player is (in the pic)?

This problem is also encountered in my code ([repo here](https://github.com/gitwikc/grid-movement-rpg/tree/with-plugin)) where the player sprite stops on free area (where there are no tiles with `collides: true`)
**PS** In my repo player is controlled by `WASD`

**Comment by gitwikc** [comment]
> Hey @gitwikc
> 
> For the first issue I can give you a simple solution. GridEngine will overwrite your character sprite's depth property. That is necessary to correctly layer all the characters with respect to each other.
> 
> In order to place the characters at the correct layer of the tilemap there is the tile layer property `ge_alwaysTop`: https://annoraaq.github.io/grid-engine/usage/layer-properties.html
> 
> If set to true on a tilemap layer, this layer will be rendered on top of all characters. There can also be several layers with this property.
> 
> However, I am currently working on a feature called _character layers_ that allows more control over layering. It will allow to have multiple char layers in your tilemap (#182)
> 
> I will try to reproduce the collision issue and come back to you.

@Annoraaq 
The new feature you are developing would surely be helpful. Are you adding any features to control the render order of the sprites and map's layers just normally as we do in Phaser? (I mean without `grid-engine` overwriting the depth property of the sprites?)

If I try setting `alwaysOnTop` property on multiple layers that are supposed to be above the player, how do I controls the render order of those layers then?

I also tried the `heightShift` property for the layers as mentioned in the docs but to no avail. The player still always renders on the top

**Comment by Annoraaq** [comment]
That is interesting... In the online example it works for me. When the character is placed at the position that is shown on your screenshot, it should be able to move in all 4 directions. Maybe we have a compatibility issue here? Did you empty the browser cache? Which browser are you using? Are there any errors logged to the console?

> The new feature you are developing would surely be helpful. Are you adding any features to control the render order of the sprites and map's layers just normally as we do in Phaser? (I mean without grid-engine overwriting the depth property of the sprites?)

Well I could allow to disable any depth setting of GridEngine, but then you need to make sure the overlapping of your characters is correct when they move. But if you only need it for placing the character on the correct layer, then I recommend just using `alwaysOnTop` instead of coding it up yourself.

> If I try setting alwaysOnTop property on multiple layers that are supposed to be above the player, how do I controls the render order of those layers then?

Then the natural order of the layers in the tilemap is taken.

> I also tried the heightShift property for the layers as mentioned in the docs but to no avail. The player still always renders on the top

This feature has a different purpose and will not solve your problem. It is only for creating several depth layers within a single tilemap layer (for example for walking through high grass). It does this by creating one layer for every tile row. This is another reason why GridEngine needs to overwrite your depth settings because it is adding more tilemap layers in this case. So when disabling the depth sorting of GridEngine, this feature would need to be disabled.

**Comment by gitwikc** [comment]
> That is interesting... In the online example it works for me. When the character is placed at the position that is shown on your screenshot, it should be able to move in all 4 directions. Maybe we have a compatibility issue here? Did you empty the browser cache? Which browser are you using? Are there any errors logged to the console?

* I checked the console but there are no errors.
* I _cleared the cache_ and tried it and then again in _incognito_ mode too. The problem still persists.

I am using **Chrome Version 93.0.4577.63 (Official Build) (64-bit)** on **Windows 7 Ultimate (64-bit)** with Service Pack 1 installed. No graphics card though

**Comment by Annoraaq** [comment]
While it is still mysterious to me why the example does not work for you I was able to observe at least some strange behavior in your repository. When I move the char there it sometimes seems to collide with free tiles randomly. Then when I push the button again it can move freely again. I will take a closer look at this and come back to you.

**Comment by gitwikc** [comment]
> While it is still mysterious to me why the example does not work for you I was able to observe at least some strange behavior in your repository. When I move the char there it sometimes seems to collide with free tiles randomly. Then when I push the button again it can move freely again. I will take a closer look at this and come back to you.

In your case when you push the button again immediately it starts moving, but then in my case I also observed the same behaviour, not on immediately repressing the button, but after waiting 3-4mins then pressing again.

Have I done something wrong during configuring `grid-engine` in my repo?

**Comment by xLink** [comment]
Adding `ge_alwaysTop` property on your `above-player` layer will fix the tops of houses being below the player, took me a little bit to figure out that it was a layer property not a tile one

As for the bug youre mentioning, Ive grabbed your repo and cant see it, the character is moving as it should and colliding with what you've set as collisions. (tested in ff & chrome, win10 etc)

I've checked over your config for grid-engine, and it looks to be fine, i will at this point point out that win7 is fairly old and could be causing your issues, by not supporting 100% the new stuff in the browsers or whatever, just a theory though

**Comment by Annoraaq** [comment]
I have found the issue why I was getting this random behavior with your repo. I am one of the lucky owners of a MacBook Pro with a butterfly keyboard that is not working properly: https://www.macrumors.com/guide/butterfly-keyboard-issues/

Your example uses WASD as for movement and my "a" key is not working reliably. Therefore the issue I experienced had nothing to do with your project 😄 

However, I have no clue why you are experiencing these issues. Maybe it is a compatibility problem. But I can't reproduce it 🤔 

Is it really that the tiles are blocking or is the game maybe freezing because of memory issues or something like that? Can you move into another direction or are all directions blocked (frozen)?

**Comment by gitwikc** [comment]
> I have found the issue why I was getting this random behavior with your repo. I am one of the lucky owners of a MacBook Pro with a butterfly keyboard that is not working properly: https://www.macrumors.com/guide/butterfly-keyboard-issues/
> 
> Your example uses WASD as for movement and my "a" key is not working reliably. Therefore the issue I experienced had nothing to do with your project 
> 
> However, I have no clue why you are experiencing these issues. Maybe it is a compatibility problem. But I can't reproduce it 
> 
> Is it really that the tiles are blocking or is the game maybe freezing because of memory issues or something like that? Can you move into another direction or are all directions blocked (frozen)?

* No, the tiles where my player unnaturally stops are non-blocking tiles. The same problem arises when I try the [basic movement](https://annoraaq.github.io/grid-engine/examples/basic-movement.html) example in the docs (as mentioned earlier).
* I can move in other directions, when I get stuck on a tile that is not supposed to be colliding. *e.g. In the basic movement example in the docs, when I [get stuck at this tile](https://github.com/Annoraaq/grid-engine/issues/191#issuecomment-918844075), I can't move right, left or down; but I can move up. In other places I can move in certain directions, but blocked in others.* So it is acts like those tiles are actually colliding tiles.
* The compatibility issue seems like the one I haven't yet checked out thoroughly. Maybe I'll look into it some more and see what I can find out. So your plugin is incompatible with older versions of windows regarding some features, then?

**Comment by gitwikc** [comment]
> Adding `ge_alwaysTop` property on your `above-player` layer will fix the tops of houses being below the player, took me a little bit to figure out that it was a layer property not a tile one
> 
> As for the bug youre mentioning, Ive grabbed your repo and cant see it, the character is moving as it should and colliding with what you've set as collisions. (tested in ff & chrome, win10 etc)
> 
> I've checked over your config for grid-engine, and it looks to be fine, i will at this point point out that win7 is fairly old and could be causing your issues, by not supporting 100% the new stuff in the browsers or whatever, just a theory though

Could you please elaborate on what new feature in modern browsers does Windows 7 not support? I'd probably try finding a workaround.

**Comment by gitwikc** [comment]
@Annoraaq
The issue is now solved on my machine!!!

### Problem :cry: 
When I started the server and the game loaded, I would instantly start pressing `W A S D` buttons and play the game. That, for some reason, used to mess up something in `grid-engine`, making it unable to identify where to collide the player sprite and where to move freely.

### Solution :partying_face: 
Now, after starting the server and seeing the game load, I didn't immediately start pressing buttons. After waiting for about 10-15 sec, I pressed the buttons; the animations run smooth and the player sprite only collides on those tiles which I have labelled to collide. I tried the same solution on your docs example too, and there was no issue.
**SO PROBLEM SOLVED!!** :smiley: :smile: 

Thank you so much for helping me out through this and checking my code to figure out the problem. :blush:
Looking forward to any awesome new features you add.

**Comment by xLink** [comment]
> Could you please elaborate on what new feature in modern browsers does Windows 7 not support? I'd probably try finding a workaround.

as i say it was just a theory, it might not even pan out to be true, but since windows doesnt even support the OS anymore with security updates, you shouldnt really be running it.

**Comment by Annoraaq** [comment]
I ma glad that you got it working 👍 

However, I still don't know what caused the issue. Moreover I can't reproduce it on my machine even when I start pressing WASD immediately after refreshing my browser window.

And you say you are having the same issue with the docs example? After loading the page you have to wait 10-15 seconds until pressing the arrow keys or it won't work?

Still mysterious 🤔
