### ISSUE TITLE
Basic example not working with typescript

### ISSUE THREAD

**Issue by ilackarms** [Annoraaq/grid-engine#207]
Maybe it's something I'm doing wrong? Very simply, typescript isn't allowing me to compile the basic example due to the error: 

```
Property 'gridEngine' does not exist on type 'Phaser.Scene'.
```

My phaser game config contains the following:

```

  plugins: {
    scene: [
      {
        key: "gridEngine",
        plugin: GridEngine,
        mapping: "gridEngine",
      },
    ],
  }
```

However I assume I need to do some extra work to map the types? Or is this not supported?

Sorry, I'm a bit inexperienced with TS/JS, so maybe it was something on my end.

**Comment by Annoraaq** [comment]
Hey @ilackarms, it seems to be this problem here: https://github.com/Annoraaq/grid-engine/discussions/47

Hope this helps.

**Comment by ilackarms** [comment]
great! thanks for the quick reply @Annoraaq !

i'm running into another issue:

`Uncaught TypeError: i.tilemapLayer is null` when calling `this.gridEngine.create(tilemap, gridEngineConfig);`

any idea what could be wrong? maybe something with my tilemap setup?

**Comment by Annoraaq** [comment]
You're welcome :)

It might be some issue with the tilemap itself. Or maybe it is not loaded correctly by phaser. It is hard to say without further information.

**Comment by ilackarms** [comment]
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/5974898/140650778-24b70616-88c2-4bd6-baa5-ba620d97efaa.png">

this is a screenshot of the map in Tiled. i posted the json here if you think that would help https://gist.github.com/ilackarms/9f810521b9c7798b96d934172208d9c7

setting up the map like so:

```javascript
  preload() {
    // load the map PNG file
    this.load.image('grassland_tiles', 'assets/img/terrain.png')
    // load the map JSON file
    this.load.tilemapTiledJSON('map', 'assets/maps/grassland_1.json')
  }

  create() {
    // create map

    var map = this.make.tilemap({ key: 'map', tileWidth: 32, tileHeight: 32 })
    var tileset = map.addTilesetImage('grassland_tiles')

    var layer = map.createLayer('Land', tileset, 0, 0)

    // create player
    this.player = new Player(this, layer)

    const gridEngineConfig = {
      characters: [
        {
          id: "player",
          sprite: this.player.sprite,
          walkingAnimationMapping: 6,
        },
      ],
    };


    // this is the line that fails
    this.gridEngine.create(map, gridEngineConfig);
  
    this.gridEngine.moveTo('player', new Phaser.Math.Vector2(15, 20));
  
  }
```

**Comment by ilackarms** [comment]
removing the 2nd layer in my tilemap resolved the issue. not sure why this fixed things but good enough for me!

**Comment by Annoraaq** [comment]
Maybe it helps if you create a layer via `createLayer()` for both of your layers like so:

```javascript
  for (let i = 0; i < map.layers.length; i++) {
    map.createLayer(i, "Cloud City", 0, 0);
  }
  ```
  
  You are only doing it for the first one in your code.

**Comment by ilackarms** [comment]
ahh thank you!
