### ISSUE TITLE
any way to get grid location of pointer?

### ISSUE THREAD

**Issue by ilackarms** [Annoraaq/grid-engine#208]
would be nice for a point-and-click style movement. currently i'm playing with the mapping from pixel location to grid location but for some reason division by tile size isn't sufficient

**Comment by ilackarms** [comment]
sorry i realize what i was doing wrong was using pointer.x/y should have been using pointer.worldX/Y

**Comment by Annoraaq** [comment]
So I guess this issue can be closed then?
