### ISSUE TITLE
Create a new method to move on a specific area?

### ISSUE THREAD

**Issue by blopa** [Annoraaq/grid-engine#216]
Hey. Frist of all thank you for this plugin, I'm using it a lot this year to learn about Phaser.

I have a situation where I'd like to move a character, but move it only in a certain area, to do something like:

![image](https://user-images.githubusercontent.com/3838114/144742004-87b6a5f3-8d93-46da-8926-7dbb3b0aaee3.png)

Do you think you will want to add this to your plugin? Because I know ways to work around it, but maybe if you have this as a feature, my code would be cleaner :grimacing: 

Thanks

**Comment by Annoraaq** [comment]
Hey @blopa, great to hear that you like GridEngine! :)

I am not sure that I understand what you want the method to do.  What would the input parameters of the method be and what should it do exactly?

**Comment by blopa** [comment]
Hey. Sorry. Let me elaborate.

Let's say we have this situation where I have a character and I want it to go to the X location: 
![image](https://user-images.githubusercontent.com/3838114/144755988-957f3971-9f64-4e66-aa53-149f6caa94e6.png)

So usually, it would take this path: 
![image](https://user-images.githubusercontent.com/3838114/144756030-ca89af2d-38ef-4534-b884-f47f35432899.png)

But I want to be able to on the fly, set which blocks it is allowed to move on, like this:
![image](https://user-images.githubusercontent.com/3838114/144756099-c6308931-dcba-45c5-94df-d6d6c74379ba.png)

So in this case, the path to the marked location would be something like:
![image](https://user-images.githubusercontent.com/3838114/144756116-b3693728-ee72-4e6d-a690-63b34c9b8a3f.png)

So I was thinking to maybe add a custom property to the `moveTo` method. Or maybe you don't think this fits the scope of your plugin, then we can close this.

**Comment by Annoraaq** [comment]
Now I understand. I think that would be useful feature for the plugin. I have to think about the best way to enable it.

One idea is to be able to pass a function as an argument to `moveTo` that specifies whether a certain grid position is allowed for pathfinding or not.

**Comment by Annoraaq** [comment]
Closed with v2.19.0
