### ISSUE TITLE
Mouse click moveTo / addCharacter & removeCharacter questions

### ISSUE THREAD

**Issue by jtopaz1** [Annoraaq/grid-engine#217]
Thank you for your efforts and hard work in creating this great software.

(1) I try to use mouse click (instead of use keyboard) to move the player. Is there any function to convert mouse X, Y to map X, Y?
This is my code:

```
this.input.on("pointerdown", function (pointer) {
	mouseX = pointer.x;
	mouseY = pointer.y;

       newMapX = ????
       newMapY = ????

	this.gridEngine.moveTo("player", { x: newMapX , y: newMapY  });
 }, this);
```

(2) I use "addCharacter" to add character id = "npc". When I try to "removeCharacter" using id = "npc" again, it throw "Uncaught Error: Character unknown: npc". This is my code:

```
const spr = this.add.sprite(0, 0, "player");
spr.scale = 1.5;
this.gridEngine.addCharacter({
    id: "npc",
    sprite: spr,
    startPosition: { x: 8, y: 12 },
});
```

```
`this.gridEngine.removeCharacter("npc");`
```

(3) I want to make teleport (player travel to another map). Any function I can use to refresh a new map?

**Comment by Annoraaq** [comment]
Hi @meta3d-ai,

(1) see #208

(2) Are you sure that the removeCharacter call itself is causing the error?  It works fine for me. You might have some other call that you are doing on the remove character that is causing this message. For example if you removed the character and afterwards try to call move() or moveTo() on it. If not, can you provide a complete and minimal example that breaks the method call?

(3) An instance of GridEngine is bound to an instance of a Phaser scene. So one way that is very common when using Phaser is to load a different scene for a different map. If that is not possible you can reload the same scene and pass it some arguments.

I hope this helps.

**Comment by meta3d-ai** [comment]
Thank you for the reply.

I just try question (3) teleport. I load another scene (the same step loading the beginning scene). However, there are 2 problems:
(a) character and object in the first scene remain on the screen. Is there any function to clear all data in the gridEngine before loading a new scene (I try removeAllCharacters, but it does not remove character)?
(b) Before loading a new scene, these three functions need to finish loading resources first (this.load.image, this.load.tilemapTiledJSON & this.load.spritesheet). I try to use promise sleep to wait for the loading, but it still fails (Error: "No map data found for key cloud-city-map1").

```
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function loadNewScene() 
{ 
	this.load.tilemapTiledJSON("cloud-city-map1", "assets/cloud_city_large.json");
		
	await sleep(2000);
	
	const cloudCityTilemap = this.make.tilemap({ key: "cloud-city-map1" });
```

thank you

**Comment by Annoraaq** [comment]
If the character remains on the screen, that means that the Phaser.Sprite is still loaded. This is independent of GridEngine.

However, GridEngine demands that you call GridEngine's create() method in the create() method of the Phaser.Scene.
If you call `removeCharacter` you are only removing the character from GridEngine. The sprite still exists and you have to destroy it yourself.

Can you provide a complete and running example that demonstrates the problem?

**Comment by Annoraaq** [comment]
@jtopaz1 Can I close this issue?
