### ISSUE TITLE
Add collision groups for characters

### ISSUE THREAD

**Issue by Annoraaq** [Annoraaq/grid-engine#220]

**Comment by Annoraaq** [comment]
closed with 1.13.0

**Comment by evan-boissonnot** [comment]
Hi.

How can I manage collision group, and collision group detection from grid engine ?

**Comment by Annoraaq** [comment]
Hey, you can pass the collision groups by passing a [CollisionConfig](https://annoraaq.github.io/grid-engine/api/config.html#collisionconfig) object to the character configuration. You can also check out the [collision groups example](https://annoraaq.github.io/grid-engine/examples/collision-groups.html).

There are two more methods for accessing or setting the collision groups of a character:
[getCollisionGroups](https://annoraaq.github.io/grid-engine/api/methods.html#getcollisiongroups)
[setCollisionGroups](https://annoraaq.github.io/grid-engine/api/methods.html#setcollisiongroups)
