### ISSUE TITLE
Isometric Offset Problem

### ISSUE THREAD

**Issue by jtopaz1** [Annoraaq/grid-engine#221]
Thank you for the detailed reply in [last post](https://github.com/Annoraaq/grid-engine/issues/218#issuecomment-999078235). I decide to use Isometric.

I try layers function in Isometric. However, I find out the game scene is different from the "Tiled Editor" scene.
I find out for Isometric, there is 2 extra fields "offsetx" & "offsety" in the "Tiled Editor" output json file. I try to search "grid-engine" source and find nothing on these 2 fields. Maybe this causes the problem.

Tiled Editor Scene:
![image](https://user-images.githubusercontent.com/93673289/147372386-88687120-96e6-48f7-809c-ea17ccc61a4d.png)

Game scene:
![image](https://user-images.githubusercontent.com/93673289/147372392-b8f2132c-5bce-455f-ae1c-04daf6398e62.png)

Best

e.g. isometric.json
`"layers":[
        {
         "data":[0, .....],
         "height":20,
         "id":1,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, ......],
         "height":20,
         "id":2,
         "name":"Tile Layer 2",
         "offsetx":0,
         "offsety":-80,
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }],`

**Comment by Annoraaq** [comment]
The representation of the tilemap in phaser is completely independent of GridEngine. GridEngine however, is responsible for placing and moving your characters. If the characters seem to be off, that could be solved by using `offsetX` and `offsetY`: https://annoraaq.github.io/grid-engine/api/config.html#characterdata

If layers are not shown correctly from Tiled, make sure you are using https://photonstorm.github.io/phaser3-docs/Phaser.Tilemaps.Tilemap.html correctly (loaded all the assets and created all the layers). Also keep an eye on the console output for errors coming from Phaser regarding the tilemap.

**Comment by Annoraaq** [comment]
@jtopaz1 Can I close this issue?
