### ISSUE TITLE
Characters that Span Multiple Tiles

### ISSUE THREAD

**Issue by Everston** [Annoraaq/grid-engine#223]
I was curious to see if multi-tile characters have been considered for the engine. 

The biggest use case is allowing for more expressive art styles. For example if you were able to set a character as spanning 2x2 tiles, the world could be built from tiles one quarter of that size, allowing for detailed features with matching collisions.

Additionally this would also allow for things such as large enemies that aren't confined to a single tile.

**Comment by Annoraaq** [comment]
They have not been considered, yet. But I think it is a good idea. I will put it on the roadmap. 
You can already add a larger sprite to the engine and center it by using the `offset` settings of GridEngine. However, collision-wise the character will only be located on a single tile at the moment.

But I think there are valid use cases for a character to cover multiple tiles for collision (like the ones mentioned by you). There are some things that have to be thought through, though. For example pathfinding. It could look for a path that makes the multi-tile character covering the target tile with any of its colliding tiles. Another way would be to give it kind of a "center" tile that would determine the pathfinding. The same considerations need to be taken when the multi-tile character is the target of a pathfinding (like when a char wants to follow the multi-tile char).

**Comment by Annoraaq** [comment]
Multi-tile characters are now supported in v2.21.0. They can be activated with the [tileWidth](https://annoraaq.github.io/grid-engine/typedoc/interfaces/CharacterData.html#tileWidth) and [tileHeight](https://annoraaq.github.io/grid-engine/typedoc/interfaces/CharacterData.html#tileHeight) properties.

There are two new examples:

- [Multi tile move to](https://annoraaq.github.io/grid-engine/examples/mult-tile-move-to.html)
- [Multi tile move to (8 directions)](https://annoraaq.github.io/grid-engine/examples/8-directions-multi-tile-move-to.html)
