### ISSUE TITLE
Turn to target direction instead move

### ISSUE THREAD

**Issue by zewa666** [Annoraaq/grid-engine#228]
the way the tile moving is implemented I guess you throttle subsequent update move calls and merge them into one tile move.

now what I'd like to achieve is that if player faces LEFT and the right arrow key is pressed a single time, instead of moving the character to the right it should be just turned to RIGHT. Holding the key should turn and move.

Havent found yet a suitable way to express that, any ideas? I played around with debounces using short intervals but than again it would need to get bypassed by the pressAndHold state.

**Comment by Annoraaq** [comment]
Hey @zewa666, could the [turnTowards(...)](https://annoraaq.github.io/grid-engine/api/methods.html#turntowards) method be what you are looking for?

**Comment by zewa666** [comment]
yes I tried that but whats funny is that a short keyup on e.g. RIGHT actually enters 4 times my update method so it turns and then also moves

**Comment by Annoraaq** [comment]
Oh, so then the problem is more that you are looking for a way to only react to a keyup event once? Phaser provides this useful method for this case: https://photonstorm.github.io/phaser3-docs/Phaser.Input.Keyboard.html#.JustUp__anchor

**Comment by zewa666** [comment]
ok so while it didn't directly helped me it at least clarified the issue is not with grid-engine but with another plugin I'm using. Thx and sorry for bothering you on this one

**Comment by Annoraaq** [comment]
No worries. Happy to help!
