### ISSUE TITLE
Introduce Game Objects

### ISSUE THREAD

**Issue by Annoraaq** [Annoraaq/grid-engine#229]
Characters are not the only objects one likes to interact with on a tile level. In most games there are also objects like chests, doors, switches and so on. Therefore it should be possible to add "GridObjects" to the map. These can be the base for adding built-in interactions on these objects in later steps.

See also #227

**Comment by notchris** [comment]
Not sure if this is helpful, but I found it easy to create a tilelayer specifically for items and make a scene reference to that layer and the tilemap. Then to check the tile at the target direction:
```js
      const { x, y } = scene.gridEngine.getFacingPosition("player");
      const target = scene.tilemap.getTileAt(x, y, false, scene.itemLayer)
```

**Comment by Annoraaq** [comment]
That is a good approach for now. The game objects will enable more convenient solutions because then GridEngine is "aware" of these objects and not just the tilemap.

**Comment by Annoraaq** [comment]
I decided to introduce labels for characters in combination with allowing characters to be added without a sprite.

For the engine everything is a character, but there might be invisible (but potentially colliding) characters. In my opinion the labeling gives the user of GridEngine more flexibility.

Some example use cases:

Objects:
Add a colliding, non-animated char and give the label "object".

Triggers:
Add a non-colliding char without a sprite and give it the label "trigger".

You can also label NPCs or players or enemies.

**Comment by Annoraaq** [comment]
Closed with v.2.18.0
