### ISSUE TITLE
moveTo always results in NO_PATH_FOUND

### ISSUE THREAD

**Issue by zewa666** [Annoraaq/grid-engine#236]
hey there, as the title suggests when I try to use moveTo on either the player or an NPC I always get above issue which I see after subscribing to the method.

any ideas where I should look at (most likely I'm doing something wrong) to track the issue down?

**Comment by zewa666** [comment]
alright I'm entirely sure I've tested that but whatsoever. Seems the only reason was that I was pointing the NPC to a blocked tile. So since the target would collide it determined not to move. Guess I'll have to calculate the next free neighbor.

Would you see some of these helper utils fit the grid-engine? Like `getFreeAdjectentTiles(tile, charId)`. CharId included because it would perhaps need to check collision groups as well

**Comment by Annoraaq** [comment]
Hey @zewa666, do I understand correctly that you are looking for a convenient way to move it to the next free neighbor instead? There is already a configuration for the `moveTo` method. Just pass a [MoveToConfig](https://annoraaq.github.io/grid-engine/api/pathfinding-configuration.html#movetoconfig) object with `NoPathFoundStrategy` set to `"CLOSEST_REACHABLE"`.

> So the question in the end is how much helpers do you want to offer for typical use cases or whether consumers are supposed to do those parts themselves using those tiny building blocks like isBlocked

The general strategy of prioritizing for GridEngine is to first provide all basic building blocks that offer a maximum amount of flexibility within the scope of the project. And then come `convenience` features that make stuff easier.

You reminded me that I forgot to add the collision groups parameter to the docs of `isBlocked`. 👍

**Comment by zewa666** [comment]
awesome, thx for the heads up with CLOSEST_REACHABLE. was fun to build it by myself but I'll gladly switch to your premade solution :)

also thanks for clarifying your strategy with the engine.
