### ISSUE TITLE
How can I get other custom properties from tiles tilemap ?

### ISSUE THREAD

**Issue by evan-boissonnot** [Annoraaq/grid-engine#237]
I want to add others properties (more than ge_collide).
For example, I want to add a next_scene propertie.

How can I get this information from grid_engine when I get a collision between player and a tile ?

**Comment by zewa666** [comment]
i think you should be able to grab them from your tileMap using `getTileAt(tileX, tileY, [nonNull], [layer])` and than looking into `properties`

**Comment by Annoraaq** [comment]
You can't get this information from GridEngine, because is is a feature of phaser tilemaps. @zewa666 is right, you can use the `properties` property of [LayerData](https://photonstorm.github.io/phaser3-docs/Phaser.Tilemaps.LayerData.html)

**Comment by Annoraaq** [comment]
@evan-boissonnot can I close this?
