### ISSUE TITLE
Extend MoveToConfig with option to control finishing observable

### ISSUE THREAD

**Issue by Annoraaq** [Annoraaq/grid-engine#241]
Add an option to MoveToConfig that controls, when the finishing observable will emit: at the beginning of the last movement or at the end. See also #239

**Comment by ok1a** [comment]
Any chance we could add an option to MoveToConfig that allows us to define whether it should be 4dir walk or 8dir walk? Similar to https://github.com/Annoraaq/grid-engine/discussions/249

**Comment by Annoraaq** [comment]
Good idea. See [my comment here](https://github.com/Annoraaq/grid-engine/discussions/249#discussion-3955888).

**Comment by Annoraaq** [comment]
Closing this because it will be solved with #250
