### ISSUE TITLE
Height shifted layer appear at the wrong depth under certain conditions

### ISSUE THREAD

**Issue by atnpgo** [Annoraaq/grid-engine#254]
When a character comes from a tile higher than the tile on the height shifted and goes one tile down past the the hight shifted tile, then comes back up before going behind it, the tile shows up behind the character when it should show up in front.

Since the description of the issue is somewhat weird and is needed to reproduce the issue, I've included a screen recording from the demo code in the /serve/ folder of the code in the master branch

https://user-images.githubusercontent.com/3844111/160238398-e25979b9-dfe8-49d7-9234-47c868d93d51.mp4

The issue is present in version 2.13.3 but not in version 2.9.1

**Comment by Annoraaq** [comment]
Thanks for reporting and also providing a good example. I will have a look at that.

**Comment by Annoraaq** [comment]
Should be fixed in 2.13.4
