### ISSUE TITLE
Deactivate collision on individual locations

### ISSUE THREAD

**Issue by zewa666** [Annoraaq/grid-engine#258]
Hey there. What would be the best approach to deactivate/activate collisions for an individual Position[] dynamically?
My use case is the following:

As shown in the image, I have predefined slots (1) where buildings can be constructed. So what I do is that I've already created the tiles for the building but used `setVisible(false)` on them. So at that moment those invisible tiles should be non-collidable. When the player interacts with the building sign (2) and starts construction, the visibility is set to true and the alpha slowly transitions from 0-1. Now the collisions should be available. Once the construction is done (3) everything is as usual 
![Collisiontoggle](https://user-images.githubusercontent.com/2861414/160257142-debc0045-6df3-43ca-ac0c-6d1d08901375.png)

**Comment by Annoraaq** [comment]
I see two solutions but there might be more:

### 1. Collision layers

You could use [collision layers](https://annoraaq.github.io/grid-engine/usage/collision-layers.html) for the collisions on your tilemap. Or simply use a collision layer additionally to your colliding tiles that will be invisible in your game. You could then dynamically change the tile at the desired position to either a colliding or a non-colliding one.

### 2. Fake characters

You can add/remove invisible but colliding characters to gridEngine at the corresponding positions.

**Comment by zewa666** [comment]
alright, I think I'll try with the collision layer as that feels like a great addition to the current ge_collide behavior

**Comment by zewa666** [comment]
Just to come back with my results. The approach I took was even easer. While setting the tiles to setVisible(false), I've also set their `properties.ge_collide` to false. And when starting the construction vice versa

**Comment by Annoraaq** [comment]
That's interesting. Unfortunately in Tiled you can only set properties in the tilemap and not for individual tiles afaik. But in phaser you seem to have more freedom.

**Comment by notchris** [comment]
If you make a reference to the tilemap you've created on your scene and the layer of the specific tiles you want to deactivate collision on, you can do:

```js
tilemap.putTileAt(-1, tileX, tileY)
```
This appears to update grid engine as well since it uses a reference to the tilemap.
