### ISSUE TITLE
Show version in console

### ISSUE THREAD

**Issue by Annoraaq** [Annoraaq/grid-engine#263]
Show GridEngine version in console for debugging purposes.

**Comment by zewa666** [comment]
It would be also great if you could put the number inside a property of the GridEngine instance as well. It would be very helpful for feature detection, for example in the DevTools, where I currently test for the presence of a method before using it.

**Comment by Annoraaq** [comment]
Yes, good point. I will expose the version as a string. For example "2.14.1".

**Comment by Annoraaq** [comment]
Will be part of next release
