### ISSUE TITLE
Observable emitting character modifications

### ISSUE THREAD

**Issue by zewa666** [Annoraaq/grid-engine#265]
Hi @Annoraaq,

my use case stems from the DevTools extension. It would be helpful to have an observable that fires when a character is deleted/added, so that I can update my select options accordingly.

Do you feel this is too specific and has not a real value for typical users? There would be alternatives for the extension like Monkey Patching the methods or observing the characters array via polling or patched via getters (proxy) but its certainly more unstable and could cause sideeffects.

**Comment by Annoraaq** [comment]
I think it is useful to offer those observables. They can be used for tools like yours and also for debugging.
