### ISSUE TITLE
Character Depth sorting

### ISSUE THREAD

**Issue by zewa666** [Annoraaq/grid-engine#275]
Hi there,

I've just realized my "objects" (3), which are characters themselves, are behaving a bit strange when it comes to order of z-index.
As you can see from the image below the NPC (1), including its name as text in the container, properly overlays the Player (2), but neither Player nor NPC can overlay the object (3).

![depth](https://user-images.githubusercontent.com/2861414/163859114-7e92f321-937f-47e1-962f-7c4afb1a5569.png)

How can this be controlled? I've tried using `setDepth` both on container of NPC/Player and Sprite of Object (note the objects do not have a container) but it didn't help either.

**Comment by Annoraaq** [comment]
Manually setting depth won't work, because the plugin automatically sets the depth based on the pixel position of the character. So characters that have a higher y position (further south on the screen) get a higher z-index.

What is the exact use case you have?
Maybe we can figure out a new feature that could help address it.

**Comment by zewa666** [comment]
Both NPC and Player are just default sprites created from the Scene, whereas the object (3) is read from a separate tiled object layer and turned into a gridEngine character. So its sprite most likely comes from a different layer. 

y position wise they are all one below the other

**Comment by Annoraaq** [comment]
Can you check if object 3 is on the same character layer as the other two?

**Comment by zewa666** [comment]
I didn't set a charLayer on any of the characters, if that is what you meant.

**Comment by Annoraaq** [comment]
Then the only difference is that the sprite of object 3 has been created automatically by phaser and not by you via scene?

**Comment by zewa666** [comment]
Lol, ok I've now spent an hour trying to replicate my scenario over at Codesandbox (https://codesandbox.io/s/patient-brook-67kmjf?file=/src/index.ts) and it works there :facepalm:

Must be another side-effect over at my side. I'll have to check again properly.

Nevertheless ... one positive side-effect is that I've managed to get a Codesandbox sample going for GridEngine. Having something like that available for Forking and as comment for an IssueTemplate might help people trying to create a shareable reproduction. Compared to Stackblitz or the likes, its possible with Codesandbox to drag&drop pngs etc. from Explorer to Browser, so uploading images for sprites/textures is easy.

**Comment by zewa666** [comment]
@Annoraaq I still have no idea why this exactly happened in my game, where my NPCs and Player got a calculated depth of 0 but the objects 2.0001008 ... :man_shrugging: 

I got it fixed doing `objSprite.setDepth(0)` after `gridEngine.addCharacter` of the object.

**Comment by Annoraaq** [comment]
2.xxx makes more sense to me than 0.

Maybe some part of your game is manually setting the depth to 0 somewhere?

If you manually override this for your other chars you might break the depth sorting of GridEngine.
