### ISSUE TITLE
how do i update the character list inside the gridEngine?

### ISSUE THREAD

**Issue by pablobion** [Annoraaq/grid-engine#276]
is there a method to exclude and include sprites from within the list?

the game is multiplayer, so when you enter the create is done

`this.gridEngine.create(cloudCityTilemap, context.gridEngineConfig);`

add/remove index in this array and that it reflects in the gridEngine.

Is there any method that updates the list?

with this I could also update the x and y data of the other players

**Comment by Annoraaq** [comment]
Are you looking for methods to add and remove characters from GridEngine after initialization? If so there are 'addCharacter' and 'removeCharacter' methods. You can also get a list of all current character IDs: https://annoraaq.github.io/grid-engine/typedoc/classes/GridEngine.html#getAllCharacters

**Comment by pablobion** [comment]
> Are you looking for methods to add and remove characters from GridEngine after initialization? If so there are 'addCharacter' and 'removeCharacter' methods. You can also get a list of all current character IDs: https://annoraaq.github.io/grid-engine/typedoc/classes/GridEngine.html#getAllCharacters

exactly, I'll try to use it later, thanks for the help!
