### ISSUE TITLE
Allow player to switch direction on short key press

### ISSUE THREAD

**Issue by notchris** [Annoraaq/grid-engine#278]
Hello, and awesome plugin! Wondering if there is a way to change the player direction on a short key press and stay on the same tile (instead of moving 1-2 tiles).  I was thinking I could override the default movement behavior, but wanted to check if there was a simpler way (couldn't find it in the docs).

Thank you!

**Comment by Annoraaq** [comment]
Hi @notchris, I also don't know a better way to achieve that. But maybe @zewa666 could find an elegant solution to this?

**Comment by zewa666** [comment]
I went with a similar approach though had additionally to care about gamepad justUp simulation which got fixed in the other plugin I've been using + an additional virtual keyboard from the rex plugin

**Comment by Annoraaq** [comment]
@notchris  Can I close this issue?

**Comment by notchris** [comment]
@Annoraaq I think so - unless you want to wait for a PR with a method with this functionality. Or maybe add the fix to to the notes on the docs page for movement. What do you think?

**Comment by Annoraaq** [comment]
I would not fix this in GridEngine, because it seems to be a general Phaser feature (handling keypresses) and not grid movement related.

However, if this is a common problem we could add it to the docs. If not, I think this issue here is suffices as documentation of the solution.
