### ISSUE TITLE
Create discussion channel for grid-engine

### ISSUE THREAD

**Issue by notchris** [Annoraaq/grid-engine#279]
This is a feature request. Can we create a discord for grid-engine to help answer questions / post snippets & ideas? I'd like to share some of the things I've figured out / ask for opinions on other things. I'm happy to set one up if it does not already exist!

**Comment by Annoraaq** [comment]
I am not too familiar with discord so I am wondering what the advantages over Github Q&A (Discussions) are.

I want to avoid having two things solving the same purpose.

**Comment by Annoraaq** [comment]
@notchris Do you have some more input on that? Otherwise I will close this issue to clean up a bit.

**Comment by notchris** [comment]
@Annoraaq Personally I think discord sparks more constant discussion around a topic. A lot of libraries have a discord channel so it's hard to say. Can we do some kind of poll or something, no one else has posted on this issue so I don't see a lot of support for the idea.

**Comment by Annoraaq** [comment]
We can also try it out and if it is not used we can still close it down again.

I think the community around GridEngine is still very small. So a poll might have too few total votes.

So feel free to create a channel if you want to.

**Comment by Raiper34** [comment]
I think gitter would be very nice for this :) Check this https://gitter.im/ only one minute setup :)

**Comment by Distortedlogic** [comment]
my vote would be discord. I find more package maintainers have discord servers than any other platform. NestJS actively tells u to avoid opening issues as the default n use their discord by default lol. less than 5% ive encountered use slack instead of discord.

**Comment by Annoraaq** [comment]
I would still consider github issues to be the main location for issues, because it allows a more structured approach than a chat. However, I will open up a discord to allow for better discussions. I can't promise I will be too active there, but I guess one important point about community is that all users can communicate, so that won't be a problem.

**Comment by Distortedlogic** [comment]
I havent join their discord yet cause I havent quite ran into a blocker that demanded it yet. But given what u said, I would just use phaser plugin channel and refer users to it in docs n such. Noise seems like a small cost relative to increased community size and activity plus ease of work required on the maintainer. If community size every grows to size to warrant its own server then could be done then.

**Comment by Annoraaq** [comment]
Sounds good. Maybe if I am in the mood some day I might create a discord server anyway. I think it is also a nice way for me to talk to the community. Announcements are easier. And also it might be a good way to ask for opinions (for feature prioritization for example).

**Comment by Annoraaq** [comment]
So it did not took too long:

https://discord.gg/PEg2Y3qD

**Comment by Raiper34** [comment]
The discord invitation is no more working. Can you fix it please?

**Comment by Raiper34** [comment]
> Thanks for letting me know. I updated the link. The new one should never expire.

But where is the new link? I do not see it. Link in Readme is still invalid.

**Comment by Annoraaq** [comment]
I updated it [here](https://github.com/Annoraaq/grid-engine/issues/279#issuecomment-1287756346). I totally forgot about the link in the readme. But it should be up to date now, too.
