### ISSUE TITLE
Issue with jest testing

### ISSUE THREAD

**Issue by muhifauzan** [Annoraaq/grid-engine#284]
I'm using `jest` for my project test and I use `grid-engine` for the `phaser` 3 engine. I got this error when trying to write some test for a file that requires `grid-engine`.

```
SyntaxError: Unexpected token 'export'

...
> 6 | import * as GridEngine from 'grid-engine';
...

at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1773:14)
at Object.<anonymous> (js/actors/Player.ts:6:1)
```

This is my `package.json`

```
{
  "scripts": {
    "test": "jest",
    ...
  },
  "devDependencies": {
    "@types/jest": "^27.5.1",
    "autoprefixer": "^10.4.4",
    "jest": "^28.1.0",
    "jest-canvas-mock": "^2.4.0",
    "jest-environment-jsdom": "^28.1.0",
    "postcss": "^8.4.12",
    "postcss-import": "^14.0.2",
    "tailwindcss": "^3.0.23",
    "ts-jest": "^28.0.2",
    "ts-node": "^10.7.0"
  },
  ...
}
```

This is my `jest.config.json`

```
import type { Config } from "@jest/types";

const config: Config.InitialOptions = {
  clearMocks: true,
  globals: {
    "ts-jest": {
      diagnostics: {
        warnOnly: true
      }
    }
  },
  preset: "ts-jest",
  setupFiles: [
    "jest-canvas-mock"
  ],
  testEnvironment: "jsdom",
  moduleNameMapper: {
    "\\.css$": "<rootDir>/js/test/mocks/style_mock.js",
    "\\.(png|svg|gif|ttf|eot)$": "<rootDir>/js/test/mocks/file_mock.js"
  },
  verbose: true
};

export default async (): Promise<Config.InitialOptions> => {
  return config;
}
```

I've tried adding `grid-engine` to `transformIgnorePatterns` option

```
// jest.config.json

...
transformIgnorePatterns: [
  "<rootDir>/node_modules/(?!grid-engine)"
]
...
```

But still got the same error. I'm not sure if it's an issue with `grid-engine` or I just miss some configuration. Please help.

**Comment by Annoraaq** [comment]
I am getting similar errors when I tried to upgrade to jest 28. Maybe it has to do with ESM but I am not sure yet. I will let you know when I find something out. You can try as a workaround to downgrade to jest 27.

**Comment by muhifauzan** [comment]
@Annoraaq I've tried downgrading to `jest@27.5.1`. But now the `jest-environment-jsdom` crashed because of the missing `testEnvironmentOptions` option which was introduced in version 28. The lib apparently doesn't pin the jest version on its end. Removing the affected lib brings me back to the original error.

**Comment by Annoraaq** [comment]
To my knowledge `jsdom` was integrated in jest until version 28. Therefore you can try to remove `jest-environment-jsdom` from your dependencies (in addition to downgrading to jest 27).

**Comment by Annoraaq** [comment]
@muhifauzan I was able to resolve the issue within grid-engine by upgrading jest AND rxjs. Maybe that solved your problem, too? Can you try with grid-engine version >= 2.17.1?

**Comment by Annoraaq** [comment]
Closed due to inactivity.
