### ISSUE TITLE
Issue with moving map

### ISSUE THREAD

**Issue by jesusMAes** [Annoraaq/grid-engine#309]
When you create a tiled map and instead on render it in 0,0, moves that map to another position (in small maps to center the screen). Collisions didnt move with it and grid engine put the collision in the place that will be if map was rendered in 0,0 instead of in 100,50. 
![colisions](https://user-images.githubusercontent.com/95760152/183736853-e329b89e-0243-4fd7-a9b3-3aff7bdb0a02.png)

**Comment by Annoraaq** [comment]
Is there a specific reason why you need to move the tile map's rendering coordinates instead of centering the camera?

**Comment by jesusMAes** [comment]
I wanna fit the game with a delimited canvas and just realised this morning that i can center the camera and use the zoom or even make black tiles surrounding the central zone to fit that. 
Sorry for the irrelevant issue xd

**Comment by Annoraaq** [comment]
No worries. Let me know if this becomes necessary for some reason. It would be possible to implement map offsets but it requires some changes.
