### ISSUE TITLE
turnTowards not working on "up-left", "down-right" etc.

### ISSUE THREAD

**Issue by Sinanaltundag** [Annoraaq/grid-engine#321]
firstly, thanks for last commit
turnTowards with normal directions works now "up" "left" etc
I am working on isometric map and cross directions not working like `this.gridEngine.turnTowards("player", "up-left");`
Can you help me

**Comment by Annoraaq** [comment]
Sure, I commented on the other bug: https://github.com/Annoraaq/grid-engine/issues/319#issuecomment-1312737266

**Comment by Sinanaltundag** [comment]
ok I close this issue, I follow the otherone
