### ISSUE TITLE
moveTo not workink on isometric map

### ISSUE THREAD

**Issue by Sinanaltundag** [Annoraaq/grid-engine#325]
I try to move character with moveTo function forexample:
`this.gridEngine.moveTo("player", {x:7 , y:4});`
when on an othogonal map command works properly but isometric map not works. 

edit: character moves one or two times to random direction when function triggered
How can I use this command on isometric map?

**Comment by Annoraaq** [comment]
Confirmed. I will look into it. Thanks for reporting.

**Comment by Annoraaq** [comment]
It should work again in v2.22.1.

**Comment by Sinanaltundag** [comment]
thanks for help, it works
