### ISSUE TITLE
when add text container, sprite goes under first tile

### ISSUE THREAD

**Issue by Sinanaltundag** [Annoraaq/grid-engine#326]
title is not understandable may be, I add screenshots, I add text and container from grid-engine example page
![before](https://user-images.githubusercontent.com/87491141/202220928-fdf5288e-8bfa-40d8-aaac-c18b1c1aaea5.png)
![after](https://user-images.githubusercontent.com/87491141/202220934-3c26ba3e-765e-4269-bff4-15925dec13e9.png)

Can I fix from somewhere?

**Comment by Annoraaq** [comment]
Can you provide more of your code?

For me it works when I merge the isometric example with the phaser container one:

https://codesandbox.io/s/sweet-moon-ipfokk?file=/src/index.js

**Comment by Sinanaltundag** [comment]
thanks for help, I compare my codes and found my bugs marked => 
it fixed wihout these lines
```
        const gridEngineConfig = {
          characters: [
            {
              id: "player",
              // => sprite: playerSprite,
              // => offsetY: -5,
              startPosition: { x: 0, y: 0 },
              offsetX: 50,              
              walkingAnimationEnabled: false,
              speed: 2,
              container,
            },
          ],
        };
```
I close issue, thanks again

**Comment by Annoraaq** [comment]
Great you hear that you could solve this 👍 

I can reproduce the issue though, if I pass the sprite additionally to the container. This is necessary if you do not use custom animations. So that might be a bug, but I did not look into it any further.
