### ISSUE TITLE
Snap character to grid when stop movement

### ISSUE THREAD

**Issue by Raiper34** [Annoraaq/grid-engine#341]
Hi,

Is it possible to configure somehow to snap the character to the nearest grid, when I stop movement? I made my own function for this snapping, but I am just curious if the Grind engine provides it out of the box.

**Comment by Annoraaq** [comment]
What do you mean exactly by "stop movement"? Do you stop the character when it is between two tiles? In Grid Engine there is no method for this purposely because that kind of goes against the philosophy of grid movement. The closest to that would be to directly set a new tile position.

Can you elaborate more on your exact use case? Maybe Grid Engine could offer something to support it.

**Comment by Raiper34** [comment]
I mean, when my character is stopped in the middle of the movement between 2 tiles using the stop() method, the character is still between the tiles after the stop and not snapped into the grid (snapped nearest tile position). If you do not understand, I can make screenshot :)

**Comment by Annoraaq** [comment]
Ok I think understand your problem. But still the following holds:

> In Grid Engine there is no method for this purposely because that kind of goes against the philosophy of grid movement.

So I am wondering which `stop` method you mean. There is only [stopMovement](https://annoraaq.github.io/grid-engine/typedoc/classes/GridEngine.html#stopMovement), which only stops an automatic movement (like follow). But that should never stop a char between two tiles. If it does, it is a bug in Grid Engine.

**Comment by Raiper34** [comment]
Ok man, my bad and misunderstanding. I used to stop movement and also I set the speed to 0. Ok, so this functionality does not exist. But I needed it, so I implemented it in my game. Here is the snippet, if anyone looking similar thing.

```ts
private snap2Grid(charName: string, charSprite: Phaser.GameObjects.Sprite): void {
    const position = this.gridEngine.getPosition(char);
    const realX = charSprite.x;
    const realY = charSprite.y;
    const x = position.x * charSprite.width;
    const y = position.y * charSprite.height;
    const XMinus = x - charSprite.width;
    const YMinus = y - charSprite.height;
    const XPlus = x + charSprite.width;
    const YPlus = y + charSprite.height;
    const nearestObj = {
      [Math.sqrt(Math.pow(realX - x, 2) + Math.pow(realY - y, 2))]: () => this.gridEngine.setPosition(charName, position),
      [Math.sqrt(Math.pow(realX - XMinus, 2) + Math.pow(realY - y, 2))]: () => this.gridEngine.setPosition(charName, {...position, x: position.x - 1}),
      [Math.sqrt(Math.pow(realX - XPlus, 2) + Math.pow(realY - y, 2))]: () => this.gridEngine.setPosition(charName, {...position, x: position.x + 1}),
      [Math.sqrt(Math.pow(realX - x, 2) + Math.pow(realY - YMinus, 2))]: () => this.gridEngine.setPosition(charName, {...position, y: position.y - 1}),
      [Math.sqrt(Math.pow(realX - x, 2) + Math.pow(realY - YPlus, 2))]: () => this.gridEngine.setPosition(charName, {...position, y: position.y + 1}),
    }
    const nearestKey = Math.min(...Object.keys(nearestObj).map(key => Number(key)));
    nearestObj[nearestKey]();
  }
```
It works for 4 direction movement only!
