### ISSUE TITLE
can I make 2 animation for one way

### ISSUE THREAD

**Issue by Sinanaltundag** [Annoraaq/grid-engine#346]
I have a car for "player" and I want to move it backward and forward, so can I move player with a selectable animation (forward or backward )

**Comment by Annoraaq** [comment]
That depends on whether you are using [custom animations](https://annoraaq.github.io/grid-engine/examples/custom-walking-animation.html) or [built-in animations](https://annoraaq.github.io/grid-engine/typedoc/interfaces/CharacterData.html#walkingAnimationMapping). With custom animations you have all the freedom that phaser provides. If you want to use built-in animations (provided by Grid Engine) you can use [setWalkingAnimationMapping](https://annoraaq.github.io/grid-engine/typedoc/classes/GridEngine.html#setWalkingAnimationMapping) to change the animation. You might also need to use [setSprite](https://annoraaq.github.io/grid-engine/typedoc/classes/GridEngine.html#setSprite) if you also need to change the sprite.

**Comment by Sinanaltundag** [comment]
thanks. I try to do
