### ISSUE TITLE
Exception creating GridEngine after scene change

### ISSUE THREAD

**Issue by a101010** [Annoraaq/grid-engine#356]
After a scene change I'm getting the following exception. I've had a look at the position I'm passing in but can't find any obvious problem.

Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at new p (GridEngine.min.js:1:1040)
    at p.clone (GridEngine.min.js:1:1069)
    at et.updatePixelPos (GridEngine.min.js:3:27552)
    at et.updateGridChar (GridEngine.min.js:3:29150)
    at et.createChar (GridEngine.min.js:3:29099)
    at new et (GridEngine.min.js:3:26073)
    at dt.addCharacter (GridEngine.min.js:3:59193)
    at GridEngine.min.js:3:66358
    at Array.forEach (<anonymous>)
    at dt.addCharacters (GridEngine.min.js:3:66342)

Code is at https://github.com/a101010/GridEngineSample

**Comment by a101010** [comment]
Maybe the problem is on the sprite? It looks like it comes in at 400, 300. But I'm not sure why it would work in the initial scene and fail in the new scenes.

**Comment by a101010** [comment]
Anyway, that should just be the coordinates for the canvas, shouldn't it?

**Comment by Annoraaq** [comment]
The error occurs because you are passing strings as coordinates. I think it happens here:

```
 const coords = val[1].split(",");
        return {
            type: "teleportTo",
            mapKey: val[0],
            pos: { x: coords[0], y: coords[1]},
        };
```

`split` being a string function will return strings.

**Comment by a101010** [comment]
Ah, thank you! Didn't think to check for that. So much javascript will take
either.

**Comment by a101010** [comment]
And of course the exceptions thrown are very helpful.
