### ISSUE TITLE
one way collision on isometric map

### ISSUE THREAD

**Issue by Sinanaltundag** [Annoraaq/grid-engine#357]
on examples one way collision is done by tile property like "ge_collide_down" etc.
is there a collide property like "ge_collide_up-right" and other directions for one way collision

**Comment by Annoraaq** [comment]
That is an excellent question and to be honest, I can't remember anymore. I took a look at the code and it should work for 
`ge_collide_up-right`, `ge_collide_up-left`,  `ge_collide_down-left`,  `ge_collide_down-right`. Can you confirm that? If so, I will update the documentation [here](https://annoraaq.github.io/grid-engine/p/tile-properties).

**Comment by Sinanaltundag** [comment]
It is surprise for me that it works :)  thanks again
