### ISSUE TITLE
collidesWithTiles always return true

### ISSUE THREAD

**Issue by Senzo13** [Annoraaq/grid-engine#377]
I think there is a problem with collidesWithTiles, they always return true, even when ge_collide does not exist anywhere

**Comment by Annoraaq** [comment]
I think this is a misunderstanding (I should make the docs more verbose about what this method does).

collidesWithTiles returns true, if the character is generally able to collide with the tilemap. Usually you determine this in the character config when adding the char to GridEngine here https://annoraaq.github.io/grid-engine/api/interfaces/CharacterData.html#collides and https://annoraaq.github.io/grid-engine/api/interfaces/CollisionConfig.html#ignoreMissingTiles.

You might be interested in https://annoraaq.github.io/grid-engine/api/classes/GridEngine.html#isBlocked or https://annoraaq.github.io/grid-engine/api/classes/GridEngine.html#isTileBlocked instead.

Sorry for the confusion. I will make it more clear in the docs.

**Comment by Senzo13** [comment]
Thank you for the information, it's very nice, I think it's great that it's active, if later by knowing Grid Engine better I can participate in the evolution of the project I wouldn't hesitate! I will look for isBlocked or isTileBlocked
