### ISSUE TITLE
ge_collide_* fails to block when moving diagonally 

### ISSUE THREAD

**Issue by onebytesolutions** [Annoraaq/grid-engine#382]
The pathfinding allows movement over blocked tiles (with the ge_collide_* property set) when moving diagonally, but works correctly when trying to enter directly (up/down/left/right).

**Comment by Annoraaq** [comment]
Do you use the [diagonal blocking properties](https://annoraaq.github.io/grid-engine/p/tile-properties)?

```
ge_collide_up-left
ge_collide_up-right
ge_collide_down-left
ge_collide_down-right
```

**Comment by onebytesolutions** [comment]
Good call - I realize now that I wasn't using those! I re-tested and it looks like there is no issue. I had to add a few extra collision helper tiles (from the ones on https://annoraaq.github.io/grid-engine/p/collision-layers/ that are basically a red square in each corner - one per direction. That way diagonal crossing would be blocked.

**Comment by Annoraaq** [comment]
I should probably update the docs such that they also mention 8dir mode.
