### ISSUE TITLE
pipeline "Light2D"  does not work correctly

### ISSUE THREAD

**Issue by Dead-TR** [Annoraaq/grid-engine#462]
If I assign the 'ge_heightShift' parameter to a layer in Tiled, lighting will not work on that layer. I understand that this is intended for overlapping objects, but is there a way to disable this? Or is it detailed somewhere in the documentation?
![image](https://github.com/Annoraaq/grid-engine/assets/63505873/968cbe4c-2dfb-4998-b1fa-237a412e6dea)
![image](https://github.com/Annoraaq/grid-engine/assets/63505873/4293cc6f-bcd6-4755-970b-8312a4637ddd)

**Comment by Dead-TR** [comment]
If I remove "ge_heightShift" then the light works. But, obviously, this is not a solution to the problem.
![image](https://github.com/Annoraaq/grid-engine/assets/63505873/312da00b-1ed5-4a43-8764-2311d959cfdb)

**Comment by Annoraaq** [comment]
I am not entirely sure how Light2D works. ge_heightShift will create one layer for each tile row under the hood. The only way to disable ge_heightShift is to remove it from the tile map.

I assume you want to keep it but fix the lighting? Can Light2D be applied to several layers at once? That would solve the problem but I am not sure about the performance.

**Comment by Dead-TR** [comment]
![image](https://github.com/Annoraaq/grid-engine/assets/63505873/0791f01b-efc0-45e7-9e2e-8fbcd9718684)
![image](https://github.com/Annoraaq/grid-engine/assets/63505873/2c9a8945-6a61-4c89-aded-fe692f3dae65)

The grid engine overlay operates using a pipeline, the same as Light2D. Because of this, I cannot simultaneously use both systems. However, since I don't want to abandon the grid engine, I will build a custom solution for the overlay. However, I think it should be mentioned.

**Comment by Annoraaq** [comment]
Grid Engine does not explicitly set a pipeline. It is simply calling [Tilemap.createBlankLayer](https://newdocs.phaser.io/docs/3.54.0/focus/Phaser.Tilemaps.Tilemap-createBlankLayer) to create the extra layers. If you check out the [MultiPipeline in the phaser docs](https://photonstorm.github.io/phaser3-docs/Phaser.Renderer.WebGL.Pipelines.MultiPipeline.html) it says:

> Virtually all Game Objects use this pipeline by default, including Sprites, Graphics and Tilemaps.

I see this as a pure Phaser thing which does not need to be mentioned again in Grid Engine. Or did you want to say that you think in the docs we should be mentioning the fact that multiple tile layers are created for the height shift?

**Comment by Dead-TR** [comment]
Indeed, you are right. It seems to be something that works inside the Phaser. I don't understand why, but if I additionally specify "setPipeline" at the end of "create", then everything works as it should. Thank you

` this.tilemap?.layers.forEach((layer) =>
  layer.tilemapLayer.setPipeline("Light2D"),
);`

![image](https://github.com/Annoraaq/grid-engine/assets/63505873/849e8ea5-03b5-4590-90e1-910057f9f664)

**Comment by Dead-TR** [comment]
Previously, I called "setPipeline" immediately after "createLayer". Looks like that was the problem. Thanks for the help!

**Comment by Annoraaq** [comment]
You're welcome.

Probably you called it before GridEngine.create? Because that will create the additional tile layers.
