### ISSUE TITLE
Example dots

### ISSUE THREAD

**Issue by scinfu** [Annoraaq/grid-engine#466]
I visited the website https://annoraaq.github.io/grid-engine/ and was very impressed with the layout of the small squares. Do you have a code example that I could use as a reference?

**Comment by Annoraaq** [comment]
Hey, I'm glad you like it.

It is hidden in the code of the docs. It's actually a Vue.js component, but it should not be a problem to use it standalone. It is basically a grid of `div`s that is animated with GridEngine. Here is [the Pathfinding example](https://github.com/Annoraaq/grid-engine/blob/master/docs/components/Pathfinding.vue).
