### ISSUE TITLE
Got IDE error message

### ISSUE THREAD

**Issue by orrest** [Annoraaq/grid-engine#473]
I'm new to `Phaser` and `grid-engine`, and it seems  I ran the demo sucessfully:

![image](https://github.com/Annoraaq/grid-engine/assets/84518085/0e187669-0aa2-4d7d-8283-0397b6396c16)

but, I've got the error message in the IDE (I've tried both VS Code and WebStorm, got the same error message):

![image](https://github.com/Annoraaq/grid-engine/assets/84518085/c69dfa13-be43-450c-bbac-2be007fe3335)

The `grid-engine` import:

![image](https://github.com/Annoraaq/grid-engine/assets/84518085/6d1c5c39-214d-4939-adc2-54e140ba57e2)

How can I remove these error messages?

Appreciate for any help.

**Comment by Annoraaq** [comment]
Hey @orrest, this is a recurring issue. See
https://github.com/Annoraaq/grid-engine/discussions/47 and https://discord.com/channels/1033320723105730611/1033320723105730614/1070409708755759214.

**Comment by orrest** [comment]
For anyone else who encounters with this problem, just declear the `GridEngine` in the `scene` class, and it will be fullfilled automatically:

```
// source: https://discord.com/channels/1033320723105730611/1033320723105730614/1070409708755759214

export class GameScene extends Phaser.Scene {

  gridEngine: GridEngine;

// use `this.gridEngine` ...
```
