### ISSUE TITLE
moveTo vs findShortestPath

### ISSUE THREAD

**Issue by taylordragoo** [Annoraaq/grid-engine#489]
Hello,

I'm currently using grid-engine in my project and I've encountered an issue related to the moveTo and findShortestPath methods.

In my application, I use findShortestPath to calculate and display the path to the user, and then use moveTo to move the character along what I believe is that path. However, I've noticed that moveTo takes into account blocked tiles and adjusts the path accordingly en route, while findShortestPath does not.

This discrepancy results in the path displayed to the user being different from the actual path the character takes.

I understand that moveTo internally calculates the path, but it seems this calculated path is not exposed to the user. Is there a way to access the path that moveTo calculates, or alternatively, make findShortestPath take into account blocked tiles in the same way moveTo does? I've read through the docs quite a bit, but still not clear to me how that would be implemented.

Any guidance or suggestions would be greatly appreciated.

Thank you for your time and for creating this useful library.

**Comment by Annoraaq** [comment]
Hey @taylordragoo,

There should not be a discrepancy between the path determined by `moveTo` and that determined by `findShortestPath` when using the appropriate settings.

They use the same code under the hood. Here are the settings that `moveTo` uses:
https://github.com/Annoraaq/grid-engine/blob/master/src/Movement/TargetMovement/TargetMovement.ts#L325-L342

Maybe you did not set the collision group of the character or something?

One other difference is that while the character is moving along the path and the path becomes suddenly blocked, it might calculate a new path based on your setting for [pathBlockedStrategy](https://annoraaq.github.io/grid-engine/api/interfaces/MoveToConfig.html#pathBlockedStrategy).

That being said, it is not possible  to expose the path of `moveTo` to the user.

If you want to separate path calculation and movement, you can calculate the path with `findShortestPath` and then use [addQueueMovement](https://annoraaq.github.io/grid-engine/api/classes/GridEngine.html#addQueueMovements) to add all movements of that path to the movement queue of the character. That has also the advantage of only calculating the path once and not twice.

**Comment by taylordragoo** [comment]
Thanks for the explanation @Annoraaq! I was definitely starting to think more likely than not it's an issue with my settings. I'll dig deeper into that and see what I can figure out. I also hit you up on discord, I'll move any other support requests to discord. Probably okay to close this issue.
