### ISSUE TITLE
Question  about "Tiled Editor" and collisions.

### ISSUE THREAD

**Issue by patrykwegrzyn** [Annoraaq/grid-engine#492]
Hi there,

Thanks for creating this awesome library!

I have a quick question: Do collisions work only with whole tiles, or can we use collision objects from the Tiled Editor as well? 
I tried to assign `ge_collide` to collision objects, but I didn't have any luck.

![image](https://github.com/Annoraaq/grid-engine/assets/7962796/742ab9b7-49f3-419d-ab08-250d5282aba1)

Many thanks
P

**Comment by Annoraaq** [comment]
Hey, I don't really know how collision objects work in Tiled, but I think they won't work in Grid Engine.

Grid Engine checks all tiles of the relevant layers for the collision property. Assuming that collision objects are not tile based in Tiled, I would say you could iterate through those, determine which tile positions they block and then set the collision properties of the Tilemap in Phaser. You could add a collision layer for this. Or you could add invisible Grid Engine characters without a sprite on the colliding positions.

Note that collisions in Grid Engine will always be tile based and not pixel based.

**Comment by patrykwegrzyn** [comment]
Thanks for the quick response, @Annoraaq! I'll stick to the Phaser way of doing it. I just wanted to make sure there isn't a way to handle it with ge.

**Comment by patrykwegrzyn** [comment]
Thanks for the quick response, @Annoraaq! I'll stick to the Phaser way of doing it. I just wanted to make sure there isn't a way to handle it with ge.
