### ISSUE TITLE
Phaser is not defined when initializes GridEngine in a ts file for scene

### ISSUE THREAD

**Issue by r000tmnt** [Annoraaq/grid-engine#495]
Hello.
I'm learning to use Phaser with Quasar framework.
The demo I want to build is a 2D roguelike scene which is suitable with grid based movement.

I follow the example in the document to set up the plugin. It seems when the triggered the create stage of the scene. The gridEngine is register but the create function does not work properly and stop the rest of the code.

I've prepared a reproduce of the bug in [codeSandbox](https://codesandbox.io/p/github/r000tmnt/web_rougelike/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzkyh74x00062a6adge3wj6y%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzkyh74x00022a6afu2pyxov%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzkyh74x00042a6akzneso5h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzkyh74x00052a6aay59s5jr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B44.13872389346618%252C55.86127610653382%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzkyh74x00022a6afu2pyxov%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzkyh74x00012a6aux2465u7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzkyh74x00022a6afu2pyxov%2522%252C%2522activeTabId%2522%253A%2522clzkyh74x00012a6aux2465u7%2522%257D%252C%2522clzkyh74x00052a6aay59s5jr%2522%253A%257B%2522id%2522%253A%2522clzkyh74x00052a6aay59s5jr%2522%252C%2522activeTabId%2522%253A%2522clzkyua3i00s72a6a3wjk4v8e%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A9000%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzkyua3i00s72a6a3wjk4v8e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2523%252F%2522%257D%255D%257D%252C%2522clzkyh74x00042a6akzneso5h%2522%253A%257B%2522id%2522%253A%2522clzkyh74x00042a6akzneso5h%2522%252C%2522activeTabId%2522%253A%2522clzkyhak400372a6a50kvcdv3%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzkyh74x00032a6aexst3qp8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clzkyh8830020dkh292c738qs%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzkyhak400372a6a50kvcdv3%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

After open up the page and run the project. Please inspect the page to see the console log.
There should be a message similar to this image.
![圖片](https://github.com/user-attachments/assets/68c901e0-244d-43fb-815c-bd4bb707410b)
Please help.

**Comment by Annoraaq** [comment]
Hey @r000tmnt, it seems that I don't have access to the codeSandbox. Is it maybe set to private?

**Comment by r000tmnt** [comment]
Hello @Annoraaq,
I've make sure the link is working this time.
Thanks for the response and plase take a look.

**Comment by Annoraaq** [comment]
GridEngine needs a global variable called `Phaser`. I am not sure why this is not set (and maybe it is also not optimal that GridEngine relies on this). However, as a workaround can you try to manually create that global variable in your scene?

Maybe `import * as Phaser from 'phaser';` is already sufficient.

**Comment by r000tmnt** [comment]
Unfortunately `import * as Phaser from 'phaser';` is not working as we thought.

**Comment by Annoraaq** [comment]
Did you try to set the global variable?
 `window.Phaser = Phaser;` for instance.

**Comment by r000tmnt** [comment]
My bad. I haven't thought about setting global variable with window.
It worked. Thanks for the help.

**Comment by Annoraaq** [comment]
You're welcome. I think we should add a cleaner solution to GridEngine that removes the need for this workaround.
