### ISSUE TITLE
Character position

### ISSUE THREAD

**Issue by andrea-barone** [Annoraaq/grid-engine#503]
**Describe the bug**
When placing a sprite on a grid that does not start at the `0, 0` position, the sprite seems to refer to an not existing grid placed at `0, 0`

**To Reproduce**
## Reproducing the Bug (Required)

Here is my current code, perhaps there is something wrong there:
```
  createTilesGrid() {
    const level = new Array(7).fill(new Array(5).fill(1))
    this.tileMap = this.make.tilemap({ data: level, tileHeight: 16, tileWidth: 16 })
    const tiles = this.tileMap.addTilesetImage('tiles')
    if (tiles) {
      const layer = this.tileMap.createLayer(0, 'tiles', 0, 200)
      if (layer) {
        layer.setInteractive()
      }
    }
    const gridEngineConfig: GridEngineConfig = {
      characters: [],
      numberOfDirections: 8
    }
    this.gridEngine.create(
      this.tileMap,
      gridEngineConfig
    )
  }

  createChamption () {
    const championSprite = 'hero'
    const sprite = this.add.sprite(0, 0, championSprite)
    sprite.setInteractive()
    const championToAdd = {
      id: 'hero',
      sprite,
      walkingAnimationMapping: 4,
      startPosition: { x: 1, y: 1 }
    }

    this.gridEngine.addCharacter(championToAdd)
  }
```

**Expected behavior**
In the following screenshot, I would expect the sprite on the highlighted cell.

**Screenshots**
![image](https://github.com/user-attachments/assets/ad9d6570-9d12-4117-9574-86f43c388698)

**Additional context**
Using phaser: 3.86, grid-engine: 2.46

**Comment by andrea-barone** [comment]
The solution was to add `offsetY` to the sprite that matches the Y positioning of the grid:
```
  createChamption () {
    const championSprite = 'hero'
    const sprite = this.add.sprite(0, 0, championSprite)
    sprite.setInteractive()
    const championToAdd = {
      id: 'hero',
      sprite,
      walkingAnimationMapping: 4,
      startPosition: { x: 1, y: 1 },
      offsetY: 200
    }

    this.gridEngine.addCharacter(championToAdd)
  }
```

**Comment by Annoraaq** [comment]
You are setting the tilemap to y:200, right?
Maybe GridEngine should position the sprite based on the tilemap and not the scene coordinates. Because setting such a  large offset seems hacky (but the only way in your situation, I guess).

**Comment by andrea-barone** [comment]
Yes, even though it's only about the starting offset, when later I change the grid offset with a calculated one
```
this.tileMap.getLayer()?.tilemapLayer.setY(this.topOffset)
```

the sprites stay alligned with the grid in the position they are supposed to even though I do not change their offset

**Comment by Annoraaq** [comment]
Are you sure about the last statement? I can reproduce your initial issue but when I set the character offset and then later set the tilemap layer y pos to something else, my character does not have the right offset anymore (as expected).

**Comment by andrea-barone** [comment]
I was reviewing my code, and you are correct, I did bound the offset of both elements and forgot about it, if I do change the position, it will go out of sync again.

**Comment by Annoraaq** [comment]
Since there are also `character layers` which contain one or several Tiled layers, it is probable more confusing than useful. People might think they positioned the character on a char layer when in reality they provided an offset. I think using the custom offset is still better.
