### ISSUE TITLE
Rebrand and refactor to GridEngine

### ISSUE THREAD

**Issue by splashsky** [Annoraaq/grid-engine#71]
Man, it's a busy day!

So per the discussion #67 where Johannes agreed that GridEngine sounded cool, I decided to go ahead and try a quick and dirty refactor of the plugin. I am pleased to announce that this refactor was successful!

I was able to get the plugin renamed to GridEngine, and all API calls now use `this.gridEngine` to access. There were no compatibility issues in any of the tests I performed, and I'll be updating the docs to use the GridEngine edition of the plugin when/if this gets approved.

Of course, there remains updating the repo here, updating the NPM registry, et cetera.

However, I can't make a PR unless Johannes approves the #70 PR and merges it, so I can rebase the branch and not double up on commits.

**Comment by Annoraaq** [comment]
@splashsky fyi: I just renamed everything. The docs, the npm package, the code and the repo. I hope I did not overlook something.
