### ISSUE TITLE
Migrate documentation from Jekyll to custom SSG

### ISSUE THREAD

**Issue by splashsky** [Annoraaq/grid-engine#80]
Having a **lot** of dependency issues with keeping the current Jekyll-based documentation consistent. I'll be shifting our documentation over to [Hugo](https://gohugo.io) since it seems a lot more consistent than Jekyll.

All this means is that adding documentation might require a build step - something I might be able to automate through GitHub Actions. This is just a wip plan at the moment.

**Comment by Annoraaq** [comment]
Sounds good to me. I only know jekyll and gatsby but anything is fine for me.

**Comment by splashsky** [comment]
Hahaha, this is a bit off topic, but this is the first JavaScript program I've ever written 🤣 

Let me know if this is a terrible way to get files from a directory...
```javascript
function findFiles(from, filter, callback) {
    if (! fs.existsSync(from)) {
        console.log("Directory doesn't exist; misconfigured?");
        return;
    }

    let files = fs.readdirSync(from);

    files.forEach(file => {
        let name = path.join(from, file);
        let stat = fs.lstatSync(name);

        if (stat.isDirectory()) {
            findFiles(name, filter, callback);
        } else if (filter.test(name)) {
            callback(name);
        }
    });
}
```

**Comment by Annoraaq** [comment]
Afaik fs is the way to go on node. So I think it is the right approach. Congrats to your first JS program 😁 👍
